[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.featurePortisContractWallet)] # 'staging' is a branch name
  command = "echo 'staging'"
  base = "/packages/react-app/"